# Основной исполнитель core_executor
# Это точка входа для выполнения скриптов kr-script
executor_core="file:///android_asset/executor.sh"
# Файл конфигурации списка страниц (можно оставить пустым)
page_list_config="file:///android_asset/kr-script/more.xml"
# Конфигурация избранных функций (можно оставить пустым)
favorite_config="file:///android_asset/kr-script/home.xml"
# Каталог инструментов (для размещения busybox и других утилит)
toolkit_dir="file:///android_asset/tools"